### ISSUE TITLE
zfs-send --raw

### ISSUE THREAD

**Issue by brussee** [alunduil/zfs-replicate#179]
For encrypted datasets the manual states it is required to add --raw to the zfs-send command to keep the dataset encrypted:
https://openzfs.github.io/openzfs-docs/man/8/zfs-send.8.html#w

Perhaps this option can be added here:
https://github.com/alunduil/zfs-replicate/blob/develop/zfs/replicate/snapshot/send.py#L54

Thanks for considering this feature request!

**Comment by alxpettit** [comment]
Just ran into this problem too. Would be much appreciated if you could add this :)

**Comment by alunduil** [comment]
After review, it looks like @brussee is correct.  We should add the `--raw` option to send as suggested (it has sane fallbacks if the volume is unencrypted).  I'll get that pull request together as soon as possible, but I would love it if you could verify the correctness of your use cases when I've got it ready.

I would also love a quick sanity check of the release pull requests I'll put together that includes this change.  Let me know if you are interested in being added as collaborators to make that easier.

**Comment by alunduil** [comment]
Alright, the pull request is attached here.  It's just waiting on review and verification that it fixes the issue.  Please add comments if you get the chance.  Once I get it merged, I'll also kick off the release process.
