### ISSUE TITLE
Test failures in NixOS build.

### ISSUE THREAD

**Issue by alunduil** [alunduil/zfs-replicate#45]
Errors can be seen at https://gist.github.com/alunduil/bfa250e4ddc49556924f1bef97b07425

**Comment by alunduil** [comment]
This should be fixed by #62 .

**Comment by pingiun** [comment]
zfs-replicate works for me on NixOS so this issue can be closed

**Comment by alunduil** [comment]
@pingiun thanks!  This issue is  reminder that I need to ensure the nix package for zfs-replicate doesn't currently run tests though.  Not that the package is broken in any fashion.  I can investigate further to see if this can be closed though.

**Comment by pingiun** [comment]
lol

**Comment by alunduil** [comment]
@pingiun was right that the tool itself works on NixOS; what stayed open here was the test run inside the nix build. Going by #432, the root of that is the hardcoded `/usr/bin/env` in the interpolated command strings, and #432 moves every zfs and ssh invocation to argv lists with `shell=False` with that prefix folded into a single constant. It landed in #474. Marking this a duplicate of #432.
